version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: facada_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - tracking_network
networks:
  tracking_network:
    external: true
